import { CTR_SHIPPING_ENUM } from './enums';

export const shippingCountrySelectArray = [
    { label: "Andorra", value: "ad" },
    { label: "United Arab Emirates", value: "ae" },
    { label: "Afghanistan", value: "af" },
    { label: "Antigua and Barbuda", value: "ag" },
    { label: "Albania", value: "al" },
    { label: "Armenia", value: "am" },
    { label: "Angola", value: "ao" },
    { label: "Argentina", value: "ar" },
    { label: "Austria", value: "at" },
    { label: "Australia", value: "au" },
    { label: "Azerbaijan", value: "az" },
    { label: "Bosnia and Herzegovina", value: "ba" },
    { label: "Barbados", value: "bb" },
    { label: "Bangladesh", value: "bd" },
    { label: "Belgium", value: "be" },
    { label: "Burkina Faso", value: "bf" },
    { label: "Bulgaria", value: "bg" },
    { label: "Bahrain", value: "bh" },
    { label: "Burundi", value: "bi" },
    { label: "Benin", value: "bj" },
    { label: "Bermuda", value: "bm" },
    { label: "Brunei", value: "bn" },
    { label: "Bolivia", value: "bo" },
    { label: "Brazil", value: "br" },
    { label: "Bahamas", value: "bs" },
    { label: "Bhutan", value: "bt" },
    { label: "Botswana", value: "bw" },
    { label: "Belarus", value: "by" },
    { label: "Belize", value: "bz" },
    { label: "Canada", value: "ca" },
    { label: "Congo, Democratic Republic of the", value: "cd" },
    { label: "Central African Republic", value: "cf" },
    { label: "Congo", value: "cg" },
    { label: "Switzerland", value: "ch" },
    { label: "Côte d'Ivoire", value: "ci" },
    { label: "Cook Islands", value: "ck" },
    { label: "Chile", value: "cl" },
    { label: "Cameroon", value: "cm" },
    { label: "China", value: "cn" },
    { label: "Colombia", value: "co" },
    { label: "Costa Rica", value: "cr" },
    { label: "Cuba", value: "cu" },
    { label: "Cabo Verde", value: "cv" },
    { label: "Cyprus", value: "cy" },
    { label: "Czech Republic", value: "cz" },
    { label: "Germany", value: "de" },
    { label: "Djibouti", value: "dj" },
    { label: "Denmark", value: "dk" },
    { label: "Dominica", value: "dm" },
    { label: "Dominican Republic", value: "do" },
    { label: "Algeria", value: "dz" },
    { label: "Ecuador", value: "ec" },
    { label: "Estonia", value: "ee" },
    { label: "Egypt", value: "eg" },
    { label: "Western Sahara", value: "eh" },
    { label: "Eritrea", value: "er" },
    { label: "Spain", value: "es" },
    { label: "Ethiopia", value: "et" },
    { label: "Finland", value: "fi" },
    { label: "Fiji", value: "fj" },
    { label: "France", value: "fr" },
    { label: "Gabon", value: "ga" },
    { label: "United Kingdom", value: "gb" },
    { label: "Grenada", value: "gd" },
    { label: "Georgia", value: "ge" },
    { label: "Ghana", value: "gh" },
    { label: "Gambia", value: "gm" },
    { label: "Guinea", value: "gn" },
    { label: "Equatorial Guinea", value: "gq" },
    { label: "Greece", value: "gr" },
    { label: "Guatemala", value: "gt" },
    { label: "Guinea-Bissau", value: "gw" },
    { label: "Guyana", value: "gy" },
    { label: "Hong Kong", value: "hk" },
    { label: "Honduras", value: "hn" },
    { label: "Croatia", value: "hr" },
    { label: "Haiti", value: "ht" },
    { label: "Hungary", value: "hu" },
    { label: "Indonesia", value: "id" },
    { label: "Ireland", value: "ie" },
    { label: "Israel", value: "il" },
    { label: "India", value: "in" },
    { label: "Iraq", value: "iq" },
    { label: "Iran", value: "ir" },
    { label: "Iceland", value: "is" },
    { label: "Italy", value: "it" },
    { label: "Jamaica", value: "jm" },
    { label: "Jordan", value: "jo" },
    { label: "Japan", value: "jp" },
    { label: "Kenya", value: "ke" },
    { label: "Kyrgyzstan", value: "kg" },
    { label: "Cambodia", value: "kh" },
    { label: "Kiribati", value: "ki" },
    { label: "Comoros", value: "km" },
    { label: "Korea, Democratic People's Republic of", value: "kp" },
    { label: "Korea, Republic of", value: "kr" },
    { label: "Kuwait", value: "kw" },
    { label: "Kazakhstan", value: "kz" },
    { label: "Laos", value: "la" },
    { label: "Lebanon", value: "lb" },
    { label: "Saint Lucia", value: "lc" },
    { label: "Liechtenstein", value: "li" },
    { label: "Sri Lanka", value: "lk" },
    { label: "Liberia", value: "lr" },
    { label: "Lesotho", value: "ls" },
    { label: "Lithuania", value: "lt" },
    { label: "Luxembourg", value: "lu" },
    { label: "Latvia", value: "lv" },
    { label: "Libya", value: "ly" },
    { label: "Morocco", value: "ma" },
    { label: "Monaco", value: "mc" },
    { label: "Moldova", value: "md" },
    { label: "Montenegro", value: "me" },
    { label: "Madagascar", value: "mg" },
    { label: "Marshall Islands", value: "mh" },
    { label: "North Macedonia", value: "mk" },
    { label: "Mali", value: "ml" },
    { label: "Myanmar", value: "mm" },
    { label: "Mongolia", value: "mn" },
    { label: "Macao", value: "mo" },
    { label: "Mauritania", value: "mr" },
    { label: "Malta", value: "mt" },
    { label: "Mauritius", value: "mu" },
    { label: "Maldives", value: "mv" },
    { label: "Malawi", value: "mw" },
    { label: "Mexico", value: "mx" },
    { label: "Malaysia", value: "my" },
    { label: "Mozambique", value: "mz" },
    { label: "Namibia", value: "na" },
    { label: "Niger", value: "ne" },
    { label: "Nigeria", value: "ng" },
    { label: "Nicaragua", value: "ni" },
    { label: "Netherlands", value: "nl" },
    { label: "Norway", value: "no" },
    { label: "Nepal", value: "np" },
    { label: "Nauru", value: "nr" },
    { label: "New Zealand", value: "nz" },
    { label: "Oman", value: "om" },
    { label: "Panama", value: "pa" },
    { label: "Peru", value: "pe" },
    { label: "Papua New Guinea", value: "pg" },
    { label: "Philippines", value: "ph" },
    { label: "Pakistan", value: "pk" },
    { label: "Poland", value: "pl" },
    { label: "Puerto Rico", value: "pr" },
    { label: "Portugal", value: "pt" },
    { label: "Palau", value: "pw" },
    { label: "Paraguay", value: "py" },
    { label: "Qatar", value: "qa" },
    { label: "Romania", value: "ro" },
    { label: "Serbia", value: "rs" },
    { label: "Russian Federation", value: "ru" },
    { label: "Rwanda", value: "rw" },
    { label: "Saudi Arabia", value: "sa" },
    { label: "Solomon Islands", value: "sb" },
    { label: "Seychelles", value: "sc" },
    { label: "Sudan", value: "sd" },
    { label: "Sweden", value: "se" },
    { label: "Singapore", value: "sg" },
    { label: "Slovenia", value: "si" },
    { label: "Slovakia", value: "sk" },
    { label: "Sierra Leone", value: "sl" },
    { label: "San Marino", value: "sm" },
    { label: "Senegal", value: "sn" },
    { label: "Somalia", value: "so" },
    { label: "Suriname", value: "sr" },
    { label: "South Sudan", value: "ss" },
    { label: "Sao Tome and Principe", value: "st" },
    { label: "El Salvador", value: "sv" },
    { label: "Syria", value: "sy" },
    { label: "Eswatini", value: "sz" },
    { label: "Chad", value: "td" },
    { label: "Togo", value: "tg" },
    { label: "Thailand", value: "th" },
    { label: "Tajikistan", value: "tj" },
    { label: "Timor-Leste", value: "tl" },
    { label: "Turkmenistan", value: "tm" },
    { label: "Tunisia", value: "tn" },
    { label: "Tonga", value: "to" },
    { label: "Turkey", value: "tr" },
    { label: "Trinidad and Tobago", value: "tt" },
    { label: "Tuvalu", value: "tv" },
    { label: "Taiwan", value: "tw" },
    { label: "Tanzania", value: "tz" },
    { label: "Ukraine", value: "ua" },
    { label: "Uganda", value: "ug" },
    { label: "USA", value: "us" },
    { label: "Uruguay", value: "uy" },
    { label: "Uzbekistan", value: "uz" },
    { label: "Saint Vincent and the Grenadines", value: "vc" },
    { label: "Venezuela", value: "ve" },
    { label: "Vietnam", value: "vn" },
    { label: "Vanuatu", value: "vu" },
    { label: "Samoa", value: "ws" },
    { label: "Kosovo", value: "xk" },
    { label: "Yemen", value: "ye" },
    { label: "South Africa", value: "za" },
    { label: "Zambia", value: "zm" },
    { label: "Zimbabwe", value: "zw" }
];

export const shippingCountryToRegion = [
    { code: "ad", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ae", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "af", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ag", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "al", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "am", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ao", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ar", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "at", region: CTR_SHIPPING_ENUM.EU },
    { code: "au", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "az", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ba", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bb", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bd", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "be", region: CTR_SHIPPING_ENUM.EU },
    { code: "bf", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bg", region: CTR_SHIPPING_ENUM.EU },
    { code: "bh", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bi", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bj", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bo", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "br", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bs", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bt", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "by", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "bz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ca", region: CTR_SHIPPING_ENUM.NORTH_AMERICA },
    { code: "cd", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cf", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ch", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ci", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ck", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cl", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "co", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cu", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cv", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "cy", region: CTR_SHIPPING_ENUM.EU },
    { code: "cz", region: CTR_SHIPPING_ENUM.CZECHIA },
    { code: "de", region: CTR_SHIPPING_ENUM.EU },
    { code: "dj", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "dk", region: CTR_SHIPPING_ENUM.EU },
    { code: "dm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "do", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "dz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ec", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ee", region: CTR_SHIPPING_ENUM.EU },
    { code: "eg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "eh", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "er", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "es", region: CTR_SHIPPING_ENUM.EU },
    { code: "et", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "fi", region: CTR_SHIPPING_ENUM.EU },
    { code: "fj", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "fr", region: CTR_SHIPPING_ENUM.EU },
    { code: "ga", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gb", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gd", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ge", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gh", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gq", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gr", region: CTR_SHIPPING_ENUM.EU },
    { code: "gt", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "gy", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "hk", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "hn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "hr", region: CTR_SHIPPING_ENUM.EU },
    { code: "ht", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "hu", region: CTR_SHIPPING_ENUM.EU },
    { code: "id", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ie", region: CTR_SHIPPING_ENUM.EU },
    { code: "il", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "in", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "iq", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ir", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "is", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "it", region: CTR_SHIPPING_ENUM.EU },
    { code: "jm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "jo", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "jp", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ke", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "kg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "kh", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ki", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "km", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "kp", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "kr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "kw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "kz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "la", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "lb", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "lc", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "li", region: CTR_SHIPPING_ENUM.EU },
    { code: "lk", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "lr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ls", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "lt", region: CTR_SHIPPING_ENUM.EU },
    { code: "lu", region: CTR_SHIPPING_ENUM.EU },
    { code: "lv", region: CTR_SHIPPING_ENUM.EU },
    { code: "ly", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ma", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mc", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "md", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "me", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mh", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mk", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ml", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mo", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mt", region: CTR_SHIPPING_ENUM.EU },
    { code: "mu", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mv", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mx", region: CTR_SHIPPING_ENUM.NORTH_AMERICA },
    { code: "my", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "mz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "na", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ne", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ng", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ni", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "nl", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "no", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "np", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "nr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "nz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "om", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "pa", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "pe", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "pg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ph", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "pk", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "pl", region: CTR_SHIPPING_ENUM.EU },
    { code: "pr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "pt", region: CTR_SHIPPING_ENUM.EU },
    { code: "pw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "py", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "qa", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ro", region: CTR_SHIPPING_ENUM.EU },
    { code: "rs", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ru", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "rw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sa", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sb", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sc", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sd", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "se", region: CTR_SHIPPING_ENUM.EU },
    { code: "sg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "si", region: CTR_SHIPPING_ENUM.EU },
    { code: "sk", region: CTR_SHIPPING_ENUM.EU },
    { code: "sl", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "so", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ss", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "st", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sv", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sy", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "sz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "td", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tg", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "th", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tj", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tl", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "to", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tr", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tt", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tv", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tw", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "tz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ua", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ug", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "us", region: CTR_SHIPPING_ENUM.NORTH_AMERICA },
    { code: "uy", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "uz", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "vc", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ve", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "vn", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "vu", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ws", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "xk", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "ye", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "za", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "zm", region: CTR_SHIPPING_ENUM.OTHER },
    { code: "zw", region: CTR_SHIPPING_ENUM.OTHER }
];
