#name: Generate a build and push to another branch
#
#on:
#  push:
#    branches:
#      - develop
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    name: Build and Push
#    steps:
#      - name: git-checkout
#        uses: actions/checkout@v2
#
#      - name: Install all dependencies
#        run: cd client && npm install
#
#      - name: Build
#        run: cd client && npm run build # The build command of your project
#
#      - name: LS
#        run: cd client && ls
#
#      - name: Push generated build to develop
#        uses: nkoppel/push-files-to-another-repository@master
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#        with:
#          source-files: 'dist/'
#          destination-username: 'SpaceBarKeepers'
#          destination-repository: 'PF_CTR'
#          destination-branch: 'develop'
#          destination-directory: 'client/'
#          commit-email: 'karel.dohnal@gmail.com'
